testonly: False
with-expecter: True
packages:
  github.com/metal-toolbox/ctrl:
    config:
      fileName: "mock_{{.InterfaceName | firstLower}}.go"
      inpackage: True
    interfaces:
      TaskHandler:
      Publisher:
      StatusPublisher:
      ConditionStatusQueryor:
      ConditionStatusPublisher:
      eventStatusAcknowleger:
      LivenessCheckin:
